### ISSUE TITLE
atomic-interactions depends on states-of-matter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/atomic-interactions#15]
atomic-interactions is importing 24 strings, images and .js files from states-of-matter.

Problems with this:

(1) The dependency is missing from package.json

(2) It creates a circular dependency, see https://github.com/phetsims/states-of-matter/issues/48

**Comment by pixelzoom** [comment]
Note that if phetsims/states-of-matter#48 is addressed, then atomic-interactions can quite legitimately depend on states-of-matter.

**Comment by jbphet** [comment]
The images, strings, and much of the JavaScript code for this sim has been moved to the states-of-matter repository, since the atomic-interactions sim is also a screen in that sim, and since we PhET developers have decided that this will be our general approach for this situation, i.e. the "parent sim" should contain all the screens and the "subset sim" should obtain its resources from the parent sim.  See https://github.com/phetsims/states-of-matter/issues/48 for more information and for a list of the commits.

I believe that this restructuring fully addresses the concerns reported in this issue.  Closing.
