### ISSUE TITLE
Overlapping touch areas in the graph

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#24]
At small interaction strength, the touch areas on the graph for custom attraction settings become incredibly overlapped (both of the custom arrows, plus the bottom line (duplicates adjustment of interaction strength - we might consider amalgamating this with the vertical arrow control, rather than having duplicate controls that overlap), plus the graph marker indicating atom position). 
![screen shot 2015-03-02 at 2 56 29 pm](https://cloud.githubusercontent.com/assets/4682895/6451564/80c2fb96-c0ec-11e4-9742-3b60cdc8b3f5.png)

We'll likely need to make a couple of changes to ameliorate this - the easiest first step will be to move the horizontal (atom diameter) adjustment arrow vertically upwards on the curve to avoid overlap.

Not sure what to do about the overlap between the graph 'dot' and the vertical adjustment arrows.

**Comment by ycarpenterphet** [comment]
Tagging @arouinfar to keep her in the loop too, since this will affect states of matter too.

**Comment by ycarpenterphet** [comment]
Also, now that the double-headed arrows are larger, we'll likely want to slightly decrease the buffer space in the touch areas on those, since their touch areas are now enormous.

**Comment by jbphet** [comment]
This has been in "status:fixed-pending-testing" status for a while, so I will assign to @phet-steele to verify.  He can delegate if he likes, since I think he's at a conference.

I just tested it, and it looks good to me.  Note that it doesn't matter if there if overlap for the touch areas for the arrow and the horizontal bar that controls the depth of the well (epsilon) since they both control the same thing.

**Comment by phet-steele** [comment]
@brroberts1231 might have a chance to look at this before me, assigning to him.

**Comment by phet-steele** [comment]
@jbphet  magnifique
