### ISSUE TITLE
oxygen atom can't achieve escape velocity, different from Java sim

### ISSUE THREAD

**Issue by jbphet** [phetsims/atomic-interactions#54]
In the original Java version of this sim, when Oxygen-Oxygen is the selected atom pair, it is possible to make the movable oxygen atom achieve "escape velocity" and go flying off the screen by grabbing it and moving it as far left as possible.  One of the design changes that was made for the HTML5 version was to make the oxygen-oxygen potential well far deeper, which is more realistic, but this makes it so that the "escape velocity" scenario never happens.  I could potentially add code to detect this case and have it behave the same as the Java sim, but I'd rather not do so unless there is a learning goal associated with this behavior.  I'm assigning to @arouinfar to decide if there is such a learning goal or if the current behavior of the HTML5 sim is acceptable.

Here is a screencast of this behavior in the Java sim:

![ai-oxygen-exit](https://cloud.githubusercontent.com/assets/3082831/17312099/8413115a-580d-11e6-9589-14ad1f20f1cd.gif)

...and here is how the same sequence of event behaves in the current master version of the HTML5 sim (and don't worry if the vibration doesn't look quite right - it's an issue with the recording):

![ai-html-oxygen-non-exit](https://cloud.githubusercontent.com/assets/3082831/17312177/23e0bb38-580e-11e6-81e7-1bc46ed22e0c.gif)

**Comment by arouinfar** [comment]
@jbphet I'm actually not sure how important the escape velocity feature is to the learning goals, since this is a little outside of my area of expertise. I wonder if this could also be related to #31.

@amyh-phet can you take a look at this issue and chime in?

**Comment by amyh-phet** [comment]
@jbphet  and @arouinfar    I'm looking into this but am having trouble getting the VPN to work so I can look at the sim.   My initial hunch is that something strange is happening here, but want to take a more in depth look.  I'll try to get to this today.

**Comment by amyh-phet** [comment]
@jbphet  or @arouinfar   Do either of you have access to the design doc?  I don't see anything in the learning goals related to escape velocity, but I find it strange that the atoms don't repel apart when you move them close together. Just don't want to introduce a misconception for students.  I was hoping to look at the design doc to see if learning goals have changed and to get an idea of the thinking behind some of the changes that were made.

**Comment by arouinfar** [comment]
It looks like you found the design doc @amyh-phet. I know some changes had to be made because the oxygen-oxygen well was not deep enough in the Java version.

>  I find it strange that the atoms don't repel apart when you move them close together.

Looking at it again, I'm also finding this a bit strange. However, I think we could make the argument that oxygen-oxygen well is deep enough that the repulsive force is not strong enough to kick out the unpinned atom.

**Comment by jbphet** [comment]
Part of the design info is in the States of Matter design doc, see https://docs.google.com/document/d/1JX9GI0SA_3diRIrqk60CPu-Ly3SVG2bWBxCuDUXO0xc/edit.  I'm not seeing a separate doc for Atomic Interactions, but I thought there was one, so perhaps @arouinfar can track it down.

In response to @amyh-phet's question, the atoms **do** repel in most cases, just not in the oxygen-oxygen case.  That's the crux of this question - whether that particular case matters.

**Comment by arouinfar** [comment]
@jbphet it looks like the design doc for Atomic Interactions is shared with the group. You can find it here https://docs.google.com/document/d/1-2v8rQlwgWwqinYYiFu8PBIpRU7HL_InBIAtwpSzBMY/edit

**Comment by arouinfar** [comment]
In the Outstanding Questions section of the doc, I found a comment Carl made in 2012:

> I have been playing with the chem sims. I noticed that on the atomic interactions one, with O on O, if you drag the one O in so it is on the steeply rising potential energy edge, above the binding energy, when released it stays bound in the well, rather than escaping. All the other sets of molecules go flying out like they should. I will probably offer some other comments on sims, but just wanted to flag this bug

In this case, I believe Carl is referring to moving the oxygen atoms very close together, such that the tracking dot is above the x-axis like this:
<img width="642" alt="screen shot 2016-08-02 at 10 40 36 am" src="https://cloud.githubusercontent.com/assets/8419308/17336929/a60038c0-589d-11e6-9df7-7786d10cd83a.png">

I haven't been able to recreate this situation for oxygen-oxygen in master, but I now think we should be able to. One of the learning goals is for students to "explain how attractive and repulsive forces govern the interaction between atoms." Since this includes repulsion, I think you'll need to add the oxygen exception  you described in your original post @jbphet. 

@amyh-phet does that sound reasonable to you?

**Comment by amyh-phet** [comment]
@jbphet    I agree with @arouinfar.  Because students can drag the oxygen atom to the left enough to move out of the potential energy well, the oxygen atoms should repel apart, causing the unpinned oxygen atom to achieve "escape velocity".   As @arouinfar mentioned, this is directly related to a learning goal, and not modeling this behavior would be incorrect scientifically and also potentially cause student confusion.

**Comment by jbphet** [comment]
Okay, thanks for looking into this - I'll add code to allow the movable oxygen atom to move away.

**Comment by jbphet** [comment]
I've added code to allow the movable oxygen atom to escape when pushed up against the pinned atom.  It now matches the behavior of the Java sim pretty well.  I think our work here is done, closing.
